"""Initial migration.

Revision ID: 45b4eb1b5a1b
Revises: 
Create Date: 2020-12-06 15:05:05.947220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b4eb1b5a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_model_department_id_fkey', 'employee_model', type_='foreignkey')
    op.create_foreign_key(None, 'employee_model', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_model', type_='foreignkey')
    op.create_foreign_key('employee_model_department_id_fkey', 'employee_model', 'department', ['department_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###
